### ISSUE TITLE
API Responses

### ISSUE THREAD

**Issue by c-myers1** [abivia/ledger#10] opened 2022-11-26 21:40 UTC
Testing some of the APIs, I note the responses are not as described in the docs. Specifically calling domain/add and currency/add gets a reply with only "time" in the response whilst the docs show a fuller response.

Do I have a wrong config somewhere?

**Comment by abivia** [comment] 2022-11-26 21:55
The test cases return the right response, so something else is going on. Possibly an error of some sort where nothing is returned. Can you share the currency/add request details? I'll try to reproduce in a test environment and see what's going on.

**Comment by c-myers1** [comment] 2022-11-26 22:02
Full disclosure: this is the latest Laravel (PHP 8.2 I suppose). I just sailed up a fresh app and pulled down Abivia. Other weird stuff going on: it created domain, ledger and currency but whilst is responds with 200 to creation of account, no record is inserted in ledger_accounts table.

Also, after installing Abivia, I manually copied the routes under vendor/abivia/ledger/routes into the routes/api file (I thought publishing config would have taken care of all that). So that's what you need to do to reproduce this.

**Comment by abivia** [comment] 2022-11-26 22:18
I see the problem and have reproduced it. You need to create the ledger first (via api/ledger/root/create), so it is a case of not reporting an error correctly. Fixing that now!

Thanks for the report.

**Comment by c-myers1** [comment] 2022-11-26 22:23
I created a domain and it created records in both ledger_domains and ledger_names. Is that a wrong way to go about it?

**Comment by abivia** [comment] 2022-11-26 22:31
That should have returned an error too. Creating the ledger sets some critical rules, mostly related to ledger accounts. Without the ledger root, not much will work. Right now it's triggering an unexpected exception and no information is being returned because there's a risk of information disclosure. However details are recorded in the audit log.

I'm going to change the exception so it's handled differently. I'm also going to set it so that at the least an unexpected exception returns a message to say the request failed. I'll add a half dozen test cases to cover this too.

**Comment by abivia** [comment] 2022-11-26 22:31
To answer your question more directly, creating the ledger root is the first thing you should do before doing anything else.

**Comment by c-myers1** [comment] 2022-11-26 22:36
I really need to understand the model better then. Since I can have multiple "domains" each having their own ledger root, I would have thought the domain comes first. Do I have things muddled up?

**Comment by abivia** [comment] 2022-11-26 22:43
Domains share the same Chart of Accounts. Each domain is a separate partition in the Journal but they all use the same CoA. The ledger root is the (hidden) parent of all top level accounts, and embeds rules like what an account code can look like, whether or not transactions can be posted to category accounts, and so on.

So the process is to create the ledger. Then you can define accounts, currencies, and domains in any order.

**Comment by c-myers1** [comment] 2022-11-26 22:49
Oh ok, reading [here](https://ledger.abivia.com/core-concepts/) again, that's actually clearly stated. But I first read that a long time ago.

So it means Abivia can't really be used to maintain accounts of multiple entities with different chart of accounts within the same Laravel application then. Correct?

**Comment by abivia** [comment] 2022-11-26 23:01
That's essentially correct. It's more designed for a single enterprise with multiple divisions/departments/etc. than a multi-tenant configuration.

**Comment by c-myers1** [comment] 2022-11-26 23:37
Very true

**Comment by abivia** [comment] 2022-11-28 01:26
Fixed in 1.9.0.

**Closed by abivia** 2022-11-28 01:26 UTC
