### ISSUE TITLE
Create Balance not working

### ISSUE THREAD

**Issue by AAUU-Ansari** [abivia/ledger#14] opened 2023-02-24 03:37 UTC
After giving code and uuid still return this error
errors
: 
[["Request requires an account code or uuid."], "Bad request.",…]
0: ["Request requires an account code or uuid."]
1:"Bad request."
2:"Request requires an account code or uuid."
time:"2023-02-24T03:35:34.008077Z"

**Comment by abivia** [comment] 2023-02-24 06:01
Can you provide a copy of the request?

**Comment by AAUU-Ansari** [comment] 2023-02-24 07:03
postData('http://127.0.0.1:8000/api/ledger/balance/query', 
		{
		  "code": "310",
		  "currency": "USD",
		 //"domain": "CORP",
		  'amount':"5000"
		}).then((data) => {
        console.log(data); // JSON data parsed by `data.json()` call
    });
![error](https://user-images.githubusercontent.com/106149988/221113980-f5f0b35d-7ba5-49b2-b11c-af64211439fa.PNG)

**Comment by abivia** [comment] 2023-02-24 07:32
I'm unable to reproduce this. Can you verify that you're running Ledger 1.10.0? I'll keep looking for a possible cause.

**Comment by abivia** [comment] 2023-03-03 20:24
Closing this. Feel free to respond and I'll reopen it.

**Closed by abivia** 2023-03-03 20:24 UTC

**Comment by AAUU-Ansari** [comment] 2023-03-08 17:24
"abivia/ledger": "^1.10",
i am using latest version but still facing a balance issue

**Comment by abivia** [comment] 2023-03-14 16:51
Still no luck trying to reproduce the problem here. Your request works as expected in our test environment.
